WIP: Feat/file to board
chaaals/is-eight-queens pull request #13
Opened 2023-10-23 14:45 UTC by marcusandrev

2023-10-23 14:53 UTC, marcusandrev commented
The code I added on app.py is to print and check imported_boards list. 

**Format:** <visualization of tile if queen (Q) or killzone (.)> <dictionary of the tile>
`.       {'id': 'killzone', 'value': 0, 'asset': 'path/to/killzone/asset'}`
`Q       {'id': 'queen', 'value': 0, 'asset': 'path/to/valid/queen/asset'}`

![image](https://github.com/chaaals/is-eight-queens/assets/69349444/82de4e8e-793d-446a-9b8b-cbd2839c00c6)
![image](https://github.com/chaaals/is-eight-queens/assets/69349444/9f927bcc-568a-45f2-a5d0-e68d5efe2ce9)

- You could see that there are a total of 92 boards, which is right naman

2023-10-23 16:02 UTC, am-cid commented
1. it's okay to use it for testing but don't track changes to `app.py` since that's where the gui will go.
2. killzone value is +1 and should increment whenever two or more queen's killzone overlap. doing it like this will make all values of every tile 0 which is not intended behavior
___
### you wouldn't have to worry about setting proper values if you do it this way:
1. use EightQueens `reset_board()` method to make `self.board` a blank board
2. iterate through the file like normal but using indices (see step 3)
3. use indices of found `Q`s to place a queen in self.board using `place_queen(row, column)`
    - this will make sure all killzones have proper values and that queens and killzones are given assets, just like if a user inputted it in interactive mode
4. after placing all queens, append `self.board` to `self.imported_boards`
5. use `reset_board()` to reset `self.board` for the next file to use

2023-10-23 16:03 UTC, am-cid requested changes, later dismissed
1. it's okay to use it for testing but don't track changes to `app.py` since that's where the gui will go.
2. killzone value is +1 and should increment whenever two or more queen's killzone overlap. doing it like what the current `file_to_board()` 
___
### you wouldn't have to worry about setting proper values if you do it this way:
1. use EightQueens `reset_board()` method to make `self.board` a blank board
2. iterate through the file like normal but using indices (see step 3)
3. use indices of found `Q`s to place a queen in self.board using `place_queen(row, column)`
    - this will make sure all killzones have proper values and that queens and killzones are given assets, just like if a user inputted it in interactive mode
4. after placing all queens, append `self.board` to `self.imported_boards`
5. use `reset_board()` to reset `self.board` for the next file to use

___
I understand that you only need to render the board so only the assets are needed but this will serve as an additional check for imported boards. it's not implied that imported boards are the solutions (although that is what we're doing now). in order to account for incorrect solutions, doing it like this will expose those

2023-10-23 16:15 UTC, am-cid commented
although if you guys want to just keep the alternate mode as just showing solutions and not what I described (a general rendering of boards in a directory), this implementation is all good. way lighter than what I suggested above, that's for sure, since it only handles assets and ids

2023-10-24 02:09 UTC, chaaals requested changes
thanks @marcusandrev ! minor changes lang naman

2023-10-24 02:09 UTC, chaaals commented on algorithm/eight_queens.py
> +        self.imported_boards = []
pa follow nalang ng standard natin for this
```suggestion
        self._imported_boards = []
```
then gawa ka nalang ng method to extract the data
```py
@property
def imported_boards():
     return self._imported_boards
```

2023-10-24 02:09 UTC, chaaals commented on app.py
> +from algorithm.eight_queens import EightQueens
same comment with cid, pa separate ng testing, app will only contain GUI

2023-10-24 14:55 UTC, chaaals approved these changes

2023-10-24 14:56 UTC, merged