placing and removing queen from board
chaaals/is-eight-queens pull request #7
Opened 2023-10-21 16:16 UTC by am-cid

closes #2
___
### highlights
1. place_queen() has a helper subfunction to avoid replacing previously placed queens's id and asset
    - eg. when a placed queen's killzone has a previously placed queen in it
2. remove_queen() has a helper subfunction to avoid removing a queen's asset and id
    - eg. when a queen is in a killzone and that killzone is about to be removed
### changes
1. add_queen() method is removed since that function is only used under place_queen. seemed redundant

2023-10-21 17:30 UTC, chaaals requested changes
For functionality and implementation, lgtm! Minor comments lang for code refactor suggestions

2023-10-21 17:30 UTC, chaaals commented on algorithm/eight_queens.py
> +        def tile_is_empty(row: int, column: int) -> bool:
```suggestion
        def is_tile_empty(row: int, column: int) -> bool:
```

2023-10-21 17:30 UTC, chaaals commented on algorithm/eight_queens.py
> +                    self._board[row][i]["asset"] = self._killzone_asset
this code snippet is repeated multiple times, might be better to create a sub function for it?
```suggestion
        def add_killzone(coord, i):
                if is_tile_empty(coord, i):
                    self._board[coord][i]["id"] = "killzone"
                    self._board[coord][i]["asset"] = self._killzone_asset
```

2023-10-21 17:30 UTC, chaaals commented on algorithm/eight_queens.py
> +        def removed_killzone_is_empty(row: int, column: int) -> bool:
```suggestion
        def is_removed_killzone_empty(row: int, column: int) -> bool:
```

2023-10-21 17:30 UTC, chaaals commented on algorithm/eight_queens.py
> +                    self._board[row][i]["asset"] = None
same comment from place queen, code snippet is repeated multiple times, might be better to create a sub fn for it
```suggestion
        def remove_killzone(coord,i):
                if is_removed_killzone_empty(coord, i):
                    self._board[coord][i]["id"] = None
                    self._board[coord][i]["asset"] = None
```

2023-10-21 17:30 UTC, chaaals commented on algorithm/eight_queens.py
Suggestion:
I was thinking if we can create a util file for `eight_queens.py`? Within the algorithm directory lang rin. I would like to hear your thoughts, please disregard this rin if tingin mo magkaka problem, di ko parin masyado gamay python hahaha
```py
# /algorithm/eight_queens_util.py
from eight_queens import EightQueens

class EightQueensUtil(EightQueens):
        # should contain all subfunctions/helper functions used in EightQueens main methods
```

2023-10-22 01:56 UTC, am-cid commented on algorithm/eight_queens.py
this would introduce inheritance problems we would need to work around. since this would inherit from `EightQueens`, we would need to use this class to initialize the board instead in app.py since `EightQueensUtil` can use `EightQueens` methods but not the other way around.

The subfunctions under `place_queen` and `remove_queen` are specific to those functions only. Your suggestion can work if:
1. the subfunctions are more general purpose
2. `EightQueensUtil` doesn't inherit from `EightQueens` but just uses classmethods to expose the methods as usable without creating an instance of it

On point 2 though, we might as well make a method within EightQueens to use, which I thought of doing but since I can only think of using that within this one function, I made it a subfunction for now

2023-10-22 01:59 UTC, am-cid commented on algorithm/eight_queens.py
> +        def tile_is_empty(row: int, column: int) -> bool:
My ocd triggered when I saw "if is_tile_empty(args):" and said "hmm that's not correct grammar". "if tile_is_empty(args)" on the other hand... But I get what you mean, convention. I'll change it

2023-10-22 03:54 UTC, chaaals approved these changes
Thanks @am-cid ! LGTM 🚀

2023-10-22 04:32 UTC, merged